spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/muxin-dev
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml
#分布式文件系统 ，虚拟机地址
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    height: 80
    width: 80
  tracker-list:
    - 172.20.10.3:22122

