spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/muxin-dev
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql
mybatis:
  mapper-locations: classpath:mapper/*.xml